name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create SSH directory
      run: mkdir -p ~/.ssh/

    - name: Add known hosts
      run: |
        echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Add SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key

    - name: Debug SSH
      run: |
          ls -la ~/.ssh
          ssh -v -i ~/.ssh/deploy_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} echo "SSH connection test"

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}       
        username: ${{ secrets.SERVER_USER }}   
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/russell/www/Portfolio-website
          git pull origin main
          npm install
          npm run build
          pm2 restart russells-website